### ISSUE TITLE
Add MapTemplate

### ISSUE THREAD

**Issue by ChazUK** [amcharts/editor4#58]
Is it possible to get the a default Map added to the editor?

I have tried adding `SimpleMapTemplate` to the templates array in `otherTemplateGroup.ts` but I'm getting the following error when trying to load the template in the UI

```
[Log] Unsupported value type: Object (geodata: [object Object]) (main.ed6a427a.chunk.js, line 1)
[Log] Unsupported value type: DataSource (geodataSource: [object Object]) (main.ed6a427a.chunk.js, line 1)
[Log] Unsupported value type: DataSource (geodataSource: [object Object]) (main.ed6a427a.chunk.js, line 1)
```

**Comment by ailon** [comment]
Unfortunately, due to technical complexities of the task Editor doesn't support Maps and there are no current plans to add the support.

**Comment by ChazUK** [comment]
Can I enquire about what the technical complexities are?

**Comment by ailon** [comment]
To be honest, the decision was made more than a year ago and I can't remember the specifics. But IIRC the problem is with loading geodata dynamically without bundling all possible permutations into the editor.
