### ISSUE TITLE
EditorLauncher should include Chart Type in save event

### ISSUE THREAD

**Issue by ChazUK** [amcharts/editor4#59]
Rendering a chart using `am4core.createFromConfig` requires a type to be provided, which at the moment is not being sent in the event object from EditorLauncher.

**Comment by ailon** [comment]
The type parameter in the `am4core.createFromConfig` is optional. Editor puts the type in the config itself so it's not needed in the `am4core.createFromConfig` call.

**Comment by ChazUK** [comment]
https://github.com/amcharts/editor4/blob/b927e8d58b10c3c527264456a69710fc497f350f/samples/react/am4editor-react-sample/src/NewChart.js#L49

add `console.log(JSON.stringify(event));`

The response does not include a type in the chartConfig object

**Comment by ailon** [comment]
Were you able to figure it out? I got a notification of a followup message from you but I can't see it on GH :)

**Comment by ChazUK** [comment]
I can see that when trying to save the event into localStorage or do any manipulation with it the `type` property is removed from the object.

```
  renderChart(event) {
    console.log(JSON.stringify(event));
    if (this.launcher) {
      this.launcher.close();
    }

    if (event.appliedThemes) {
      this.applyChartThemes(event.appliedThemes);
    }

    if (this.chart !== undefined) {
      this.chart.dispose();
    }

    this.chart = am4core.createFromConfig(
      event.chartConfig,
      document.getElementById("chartdiv")
    );

    const charts = JSON.parse(localStorage.getItem("charts"));
    charts.push(event);
    console.log(charts);
    localStorage.setItem("charts", JSON.stringify(charts));
    console.log(localStorage.getItem("charts"));
  }
```

The initial stringify of the event `"chartConfig":{"type":"PieChart3D" ...` then adding that to an empty array removes the type property.

**Comment by ailon** [comment]
Hard to say. Could be that `type` is some sort of reserved keyword somewhere and gets removed/swallowed/etc. But there's nothing we can do about it on the editor's side as it is what is needed for the charts.

A quick workaround would be to save that type separately and then pass it to `createFromConfig` as a parameter.

**Comment by ailon** [comment]
Having said that "type" is used throughout the JSON config on lower levels for all kinds of objects. So if those are removed as well, the above workaround won't work.

**Comment by ChazUK** [comment]
I think it's something to do with the object itself, possibly omitting it from the model. Here you can see I've printed, and the second console log object doesn't contain type property.

```
    console.log(JSON.stringify(event.chartConfig));
    console.log(event.chartConfig);
    console.log("----");
```

<img width="1081" alt="Screenshot 2021-07-14 at 11 29 16" src="https://user-images.githubusercontent.com/768108/125607699-145de7f9-1020-4248-addc-84283ff29cd4.png">

Then after just running a console.log on a copy pasted version of the object displays it displays type.

<img width="1378" alt="Screenshot 2021-07-14 at 11 29 45" src="https://user-images.githubusercontent.com/768108/125607707-57354512-db8f-4d24-ae28-7ce8ec8b30f7.png">

**Comment by ailon** [comment]
Not sure I understand. I see type in both of your screenshots. What am I missing?

**Comment by ChazUK** [comment]
Maybe this will show it better, even though type is listed on the top row, it seems to be a hidden or private property on the model that is not being copied properly.

![typemissing](https://user-images.githubusercontent.com/768108/125608970-4efdd224-60ed-4982-9a8f-4b4e837129dc.png)

**Comment by ailon** [comment]
But the "unexpanded" first line has `type`. And if you `console.log(event.chartConfig.type)` I'm almost certain you'll get it. So I'm not sure if we are debugging browser devtools here or is there a real issue you are hitting? :)

**Comment by ailon** [comment]
Btw, you shouldn't pass the actual config object to `createFromConfig()` if you plan to reuse it later. The charts, unfortunately, modify the config in process. You'd need to create a copy before passing it if you want to retain the "original".

**Comment by ChazUK** [comment]
Ok, can you try 

```
import cloneDeep from 'lodash/cloneDeep';
...

const config = cloneDeep(event);
console.log(event);
console.log(config);
```

and see that type is being removed from the chartConfig object

<img width="866" alt="Screenshot 2021-07-14 at 12 38 44" src="https://user-images.githubusercontent.com/768108/125615939-386095b0-59be-4de9-8541-0d11e51a75a6.png">

**Comment by ailon** [comment]
What are you passing to the `createFromConfig()` later on?

**Comment by ChazUK** [comment]
As pasted above I'm storing the event response object in an array, then converting to JSON string to store in localStorage.

Then on the EditChart.js page I am taking the string from localStorage, parsing the JSON and then looping through the array, passing 

```

**Comment by ailon** [comment]
OK, I've tried to do a simple demo mod to store the config in `localStorage` on the new chart page and then get it on the edit chart page. Here it is https://codesandbox.io/s/amcharts-editor-localstorage-sample-b5qe6

Seems to be working for me. The only two changes from the demo bundled with the Editor are:

Line 50 in NewChart.js:
```
localStorage.setItem("chartConfig", JSON.stringify(event.chartConfig));
```

Line 135 in EditChart.js:
```
chartConfig = JSON.parse(localStorage.getItem("chartConfig"));
```

I still think that the issue in your case is that you are passing the config to charts at some point before you save it or after you retrieve it and that causes the config to get modified. Hard to say without seeing a [non]working example.

**Comment by ChazUK** [comment]
https://codesandbox.io/s/amcharts-editor-localstorage-sample-forked-d474y?file=/src/NewChart.js
line 45 - 51

1. Click New Chart
2. Click the box to open amcharts editor
3. Select 3D Donut Chart
4. Click Save
5. Compare console log for event, cloneDeep and JSON steps . type is missing from cloneDeep copy.

JSON.parse(JSON.stringify()) is a costly way of copying an object.

**Comment by ailon** [comment]
I'm not sure if I want to get into debugging cloneDeep or other things here. Maybe it is treating "type" in some special way or anything. I'm not willing to go investigating it, sorry.

`JSON.stringify()` maybe costly if you are doing it in a big loop or something but here it just works, doesn't require 3rd party dependencies, and the "costs" are negligible, imho.

**Comment by ChazUK** [comment]
Ok, I've never seen this issue happen with cloneDeep before. Hopefully no one else will come across this issue.
