### ISSUE TITLE
DOMException error in unicode

### ISSUE THREAD

**Issue by lhagwasuren** [amcharts/editor4#80]
Hi.
I'm having trouble building amchart 4 editor.
When I use unicode character, it throws me DOMException error.
I'm using vue to use the amchart editor.
As we can see in the image below, when using with the unicode this gives me btoa error.
![image](https://user-images.githubusercontent.com/50734813/151475884-29fef662-1003-4fb4-a45c-69de1e06e911.png)

Thank you.

**Comment by ailon** [comment]
This should've been fixed in the latest release (4.0.3) published about a week ago.

**Comment by lhagwasuren** [comment]
Nice. Thank you so much. 😊
